# Site settings
title: Coinomi
email: 
description: "Next generation cryptocurrency bank"
baseurl: "http://www.coinomi.com"
url: "http://www.coinomi.com"

# Build settings
markdown: kramdown
permalink: pretty

# Less
lessc: /usr/bin/env lessc